const baseStats = {
  hp: 100,
  jumpFreq: 0.1,
  moveFreq: 1,
  dirFreq: 1,
  moveSpeed: 0.2,
  moveDrag: 0,
  projType: "PROJ",
  projFreq: 5,
  projForce: 10,
  collision: true,
  swim: true,
  flight: false,
};

const weaponStats = {
  force: 5,
  freq: 0.5,
  proj: "PROJ",
};

const ENT_DATA = {
  PLAYER: {
    label: "Player",
    ctor: Player,
    image: ["....aaaa...", "...aahhh....", "...aahhh....", "...aaaa.....", "..aaaaaa....", "..aaaaat....", "..aaaatt....", "..aaattt....", "..aatttt....", "..aatttt....", "..aallrr....", "..aallrr....", "..aallrr....", "..aallrr....", "..a.llrr...."],
    colors: {
      a: "rgba(78, 54, 50, 1)",
      h: "rgba(51, 19, 73, 1)",
      t: "rgba(71, 30, 128, 1)",
      g: "rgba(78, 54, 50, 1)",
      d: "rgba(177, 136, 136, 1)",
      l: "rgba(50, 11, 65, 1)",
      r: "rgba(64, 19, 78, 1)",
    },
    stats: {
      hp: 100,
      jumpFreq: baseStats.jumpFreq,
      moveFreq: baseStats.moveFreq,
      moveSpeed: 0.2,
      moveDrag: 0.1,
      projFreq: baseStats.atkFreq,
      projType: "PROJ",
      projForce: 20,
      swim: baseStats.swim,
      flight: baseStats.flight,
    },
  },
  charlie: {
    label: "charlie",
    ctor: Mob,
    image: [
      "........................................................................................................................................................................................................",
      "........................................................................................................................................................................................................",
      "........................................................................................................................................................................................................",
      "........................................................................................................................................................................................................",
      "........................................................................................................................................................................................................",
      "........................................................................................................................................................................................................",
      "........................................................................................................................................................................................................",
      "........................................................................................................................................................................................................",
      "........................................................................................................................................................................................................",
      "........................................................................................................................................................................................................",
      "........................................................................................................................................................................................................",
      "..............................................................................................................................abbcca....................................................................",
      "...................................................................................................................deebeeefgfebcccchiha.................................................................",
      "........................................................................................................ajkebbbeeehbbeeheekfhjbcccceihcc................................................................",
      ".....................................................................................akbelcccbecccccccbedebcbccebekkmmmhhekkeeebcbbbhbebccc.............................................................",
      "..................................................................................dlnmcblebblkbcbeclclcecbecbbhebemmmmfmmhehebbebbbbcbhjccccc...........................................................",
      "...............................................................................eeoomoebebbeebbcbllllcccbeceebbbeelmmmommmfeeheehjhbcbbejccbcccp.........................................................",
      "..........................................................................dobeblmoqoodeeebebbllcllllllllceooebecebbrhmboomeofohhhimbbrcbjcccclljbb......................................................",
      ".......................................................................adoerrrceeoooededebbrbcccllllccllcreobebbrrbrheoeedooeommisfhghtccbccclciheuv....................................................",
      "..................................................................sqooeeoeoooeeoooeodedeeobrclllllllllrllclleeehrbrdbbeheororeqeeeowxxsgtyvyibcccceghjvzA...............................................",
      "...............................................................BqmooeoeeoeoooomoooeeederrrbbcclcccclllclllllhrderrrbeeooeoeqqerooeeqqegCDxxCsbbccccbjivEuFG.............................................",
      "..........................................................aufomomomqooeeeeooeeoedbrrrrdebbrcclllcclaalaalllllcrebcblcdeemoooomeqoeemoeooiEHxCcsjiIccficccbtFFF..........................................",
      "..........................................................ggnqoooedeeoeoomeeeeeeebeeeebbbrcrcclllllallalllccllbobcbcrrebenooemooemoeeeeehuCuxshbgJKtcccccbbLFFFF........................................",
      "..........................................................nnooeeddommmmoooeeeoooeeberrrrrlclllllllllllalllccclrrbbrrrrrbeeomomoddeoqooeoeehDiMthbECNbccccbbfgAFFFF......................................",
      ".........................................................xooeeeeoeommqoemooeddrrrberrclllllcclllllllllllllcrrerrbebrbreerbeeeeeoooeoeeeqhddeeooohhvDvLclcbccbbjOFFOOF...................................",
      ".........................................................ooeeeqoqooomoeeomeeebrrlebrclllcrcccrlllalllcabllcrcbrrbrerrbberrbeeeeeooeedebfeeeeoeeoeekwwulccbbcjbctOOFFOF..................................",
      ".......................................................PeeerooqmomoqeeeeeoeddbcrddbrllccrbccllllllllllllllrcheobecrberrceeclreebeeedeemebbedererbbeeebeebbbccccccQOOOOOA................................",
      ".......................................................ooereeomqmoomeeeeoeeeoeeebrcrrrrrrcrlllllcllllllllbrrromoebrbbrrbreebcrbbrrbbbebobeeeeereerbeeheeebbcccccccOOOOOF................................",
      ".......................................................eeeomoooeeoeeeedorrrrrbbrrbrlbcrcrcllccelclllcllllccrdroeeeeeeeeebrreerlebbrrbbbrbebeeeeebbberbbbebecccccccgiROFF................................",
      "......................................................eeeooomooeeeneoeoeebrrrddrbrrrrmrrrclllcrclllrcelbcrrrddeeqeoehebbbebrdorrreebbberrbbereehbbbrrrerbbbmccccccebDOOF................................",
      ".....................................................aoeoeoooooeoqneeddrrebbemerrrbbrlcbrlbllfcllblccrelrberrodoeeocbebbercrrofccrrbreebeerbrrdoeehebrrrrbbbcccccbjbEzFF................................",
      ".....................................................eeeeooeereedmedeeeddbdeeedrllccbbrccbrrbrllcrebrcdrrbboeoeoeeerreeeebrerrrrrrlrrrrrrobbeddobbbeebrbbrbbbbbbbcbbixxFs...............................",
      ".....................................................eeemooeeeeeeoeeededereeerrclrllerrrrcererrdmmrrdrddbdbdeeredeeeereeebcebrrbrbbbrerbrrebbeeerebremebrrrrbbbbbbbccDxNF...............................",
      "....................................................eoeeebrredededrdeeeeroeemddberdoledbrddeeedreedrdreddeedooooeereeecrrdrbbeerbebrbrbbebbrrberrrrrerebbbbeccbbbbjjcbkxx...............................",
      "...................................................oeoeeerbbreeeedoreeddeodeddrrrdeoeddbdddeoedeoeeeeeedeooeeeoqeedeebbbrebbrrbrebrbbebrrrrcrrebrrrbrreebcrbccrrbbjbcbbSx...............................",
      "..................................................ooeeebberreeedrrdeeobberoderrreooeeeoedeoeoooeddeeeedeeeeeeederrdrdrrbrerrbebcbrebrrccccrrrebrrrrbcrbbbccbrrlccbhjhcbhh...............................",
      "..................................................oeeerbbrrreebrbreeoeerdedeedreemedededoeoeqoooeTTTeTeooTodqTTerrrrrbeerrbbrbbbrrrbebcrrrrrbrbrrrbrbrrrrcccccccrbhebbebb...............................",
      ".................................................eeoeererrbrerrbrdooqrlereeerrrTTeeoTTeTToooqqoooTTToTTdeTmeeTTdrrbrrrrerrrrrrrrrrrrcrrrrcbrerbbercrrcrrcccllrccbrbebbbbbt..............................",
      "................................................hhebbrebbbeberrreedoerTTmrdeedoTToTTTTooUooqqqqUUooToTTTeeeoTeedrrrrrrrbrbrbrlbrrcrrrrrrrrrbhrrrrrreclccbcclccllcbebhebbcc..............................",
      "..............................................agebrrbrbrcrberrrbrroerboddoeeToUTTTTUToUUoUqUqUqUUUUTUUTeTTTedeedrrrrrlcrrrbbrrrbrrbcclrrbrberrrccccccbcccccclccrrebbffeccc..............................",
      "..............................................imbbbrbrcrrrbrbrcbddorroeoedeTUVoTUTUoUUUqoqqqUUqUUUUUUoUTVVTeTVddrerberrrcccrrrebcrrrbcccbebllrrclllccccrccccccccrrbmsbcccc..............................",
      ".............................................kgobbrrrrbrbrrrrrbbmeoreTmddeoUUoooToUUqUUUqqWWUqWUUqUoToqTTTTeVVddrrdbbbbrrrrrbbrrreebbbbrrbrllbrlllllcccccccrcllccrbbfebcbb..............................",
      "...........................................ehhherbrrcbrrberecreoddreerVTVoUTToTUoUTUUWWUWqWWWWqqqUUUUoUTVVUTVedrrrrrbbrcerrreerrrcrccrrcrcclcrcllcllcrlccccbccllccccbebbbh..............................",
      "..........................................hmmherbbbecrrrerbbbbedrrrddVVdToToTTqTUoUUUqWUqWWUqWWWWUWqUoTTTTUTeTrrrrdbrebrlrrrrbrlrcrlllcccllcbrlllclcrrrclcbccccccccccbebbm..............................",
      ".........................................ekfhfrreerhccrchcordebrdreedeTToTooTTUTUUqqqWWWWWUWWWWqWWWWUUToVTooVVrrrrrrbrdqccrrbbrlrrlccbcclllcrrccrccccrrrcccclclccccccrebbh..............................",
      "........................................jmkmmebrbrbreccerceembbrredTrVeToTTTToToUUqqqqWqUWWWWWWWWWqWUUUoVVTTTVddeVrrrerbrbcreecclccclllbccccrcllclcccccccccccclccrcccbbeee..............................",
      ".......................................jhfmohbrrbrrcbcrrbbedrbddVeedVeeVVTTTooTUqUUqUWWqWUWWWWnWWWUWqqUUUTUTdVeeddrrrrdrrrrrebrrrlllcclcrccllcclllcccccclcclcccccccccbbeeb..............................",
      ".......................................mmmmeberrrberbrrbebcrbededeeTTToTVTooTToUUqqUWWWWWWWnWnWWWWWUWWUqUTqTTVVVrrrrrrrrrrdrdrrrcclcccrbrclcllllclllcccccrcclccbccccchggihb.............................",
      "......................................nffmoeebcebbrrcbhbcllcbrdddeVVdeVVTTToToUqqWUWWWWWWWWnWXWXWWWWWWqUUoUUTTTVdddrrrrredrdVrcrrcccccclllclrllllccclccllccclcbbcccccbmfmee.............................",
      ".....................................hcfmoebbrrlcbreecllcrrbrbdeeTVVrddVTTTToUUUqWWWWWXWXWWXXXXWWWWWUUWqUUTTTVVVdrdeerrrrrddlcccrccclllllclcccccccccclccccccccllcccccllrcmf.............................",
      ".....................................ttffmeerrlcrrlcclclllrrrcdrdddrVVTVToooUUUUUWWWWWWXXXWXXXXXXXXWWUqqqUUTTTddVdrdrrrrdrdllllrclcclclllcllcccccrcccllcccclclcccccrclcrbbf.............................",
      ".....................................jcmmooebrllcccclccclrrrrbrddrTddVTToTToUUUUqWWWXWXXXWXXXXXXXXXXWWUWqqUTTVVVVddddrrrrdrlllrlllclcclllclclccrrccrccccccclccccccrcccccbbm.............................",
      "....................................chmmoeebbrlcclclccrcccrbrrbcrrrVVTTTooTUUUqWWWWWWXXqXXXXXXWXXXXXXXWUUqUUoTVVdrVrrrrrdrrrlllllllrrllclcccclrcccclcccccbcccccccrrcclcccmf.............................",
      "....................................cjmmoeebrrcccclcbbcccrrcrrcrrrrVVVTVoTUUUUqqWWWWWWXXXXXWXXXXXXXXXXWWUqUUUUVVTVrVrrrdrrrrrrlllclrcllcclccccccccccclrccclccccccccllccccrf.............................",
      "....................................jmmooerebcclrrjbbehcllcrrcllrddeTTTTVUqUqWWWWWXXXXXXYYXXXXXXXXXXXXXWWWUUTUVTTTVVTdrrrdrrrrrrorrrrrccrrcrrlllclllccclllccllcclcclllcccrha............................",
      "....................................tmmooebrbrlllrllbcrlllcccclrrdVTTToUUqqqWWWWWWXXXYYXYYXYYXXXXXXXXXXWWWWUoUTVTTTVVrerdddrdrrmrrrrrrrcrrrcrccclllllclclllcclcllllcllcllchh............................",
      "....................................mhhheerccelcllllcccllccllrrrrVVTTTTTqqZZWWXXXXXXYXYYYYYYYYXXYYXXYXYXXWZZZUUTVVTVTTVddrddVTddrrrrrrrrrrrccrrrbbcllllllllcccccccllllccclso............................",
      "...................................thhebbbbccbccllllcccllcllcrrrVTToTUTZZWZWWXWXXXXXYYYYYYYYYYYYYYYXYYXYXWWWZqUoVTToTTTVVVVTTVVVVdrdrrrrrrrclllcllllcllllclccclllcclcllllljm............................",
      "...................................bheebebbrcrhbclllccccllccrrrdVTTTqTZWWWWWWXXXXYYYYYYYYYYYXYYYXXYYXYXXXXWWZZUUoVTTToTTrTddVVVVVVdrrrrcrrbrrccccclllllllllllllllcclcllllcch............................",
      "...................................thbbrcebrrlbeclllllcllccrlcVTTUodUWWWWWWXXXXXXYYY00Y00YYYXYYYXYXYYYYYXXXXWWZZUUVTVooTVTdVVddVVVVdrrdrrrrrccccclllllllllllllllcclllcccbrjh............................",
      "..................................ajebrrcrbrclcrcrcllclcccclrrVTTTVUWWWWWWXXXXXYYY0Y00000YYYYYYYYYYXYYXXYXXXWWZZUoUVTVToTTTVTToVVVVVdVddrbrrrrclcbllllllllllllccccclcclccceh............................",
      "..................................hhbbbcrbrcccllcrccllllccrrrddrrqWWWWWWZWXXXXYYY0Y000000Y0YYYY0YYYYYYYYYYXXXWWWZZUUTVVToUqUUqTooTTeVVeeVVdrrrrcccllllllllllllllclllcllcccrh............................",
      "..................................hhbbbcrlrccrlcrcrclcllllrrddeoUWWWWWWWWXXXXYY0000000000YYY0Y00YY0YYYYYYYYYXWXWWZZUUoTTTooUUUUoTVVTooTVeVVrrrrrcccllllllllcllrlccllllllccef............................",
      "..................................mbbbrrrrrrebrcllcrcllccrdeTUZWWWZWWZWWXXXYYY000001010000000000YYYYYYYYYYYYYXXXXXXWWZoUTTTTTUoUUUqqqqUoTTTTVerrccrcllllllllccclllllllllllrg............................",
      "..................................hhbrrrrbrbrbercccllllcrbTToqZWWUWWZWWXXXXYY000101000000000Y0000Y0YYYYYYYYYYYXYYXXXXWWUZUUUZZqZWWWqZWqUoTTTeeVrrrrrlllcllcrccllllllllllllrM............................",
      "..................................mehrccccccrrrrrcllllcbbeTTqqWWWWWWWWWXXXYYY0001111000000000Y000YYYY0YYYYYYYYXYYYYXXXXXZWZZZZZZWWWWWWWqUUoTTTTddrbbcccclcclllllllllllllllcm............................",
      "..................................hhclbbclcclrlcrcllcbVeeeTUqWZWqWWWWWXXXYY00000111100010YY000000YY00YYYYYY00YYXYYYYYYYXXXXWWWWqZWWWWXWWWqqqoooTeeebrcccccclllllllllllllllch............................",
      "..................................hblcclcbcrccerccccbbeTooUoWWWWWqWWWWWXYY0001000100000000000XXYYYY0YYY0YY0000YYYYYYYYYYYYXXYXnWWWXWWXnnnWWqqUUooTeerrrcccclllllllllllllllcb............................",
      "..................................bbbbccclclclcllcbbeoToUUqWWXqWWWWWWXXYYY000000000000000Y0000YYYYYY00Y0YY00000YYYYYYYYYYYYYYYYYYXYYYXXXXnnWWqqqUooeebrcrcclllllalllllllllca............................",
      "..................................jcjrcccccclcllcbeoTToUUqWnnXWWWXXXXXYY00000000000000000000000YYYYY0000000YYY0YYYYYYYYYYYYYYYYYYYYYYXXXXXXWWWWqqqoobbbrrccllllllalllllllll.............................",
      "..................................bchrclclccllllrreTTooUnWXXXnnnXXXYYYY0Y0YYY0Y00Y00YY0Y00Y0YYYYYYYY0Y00YYYYYYYYYYYYYYYYYYYXYYYYYYYYYYXXXXXXnnnWWWqqoerrrccclcllllaallllll..............................",
      "..................................bttbcclclllllccreeooUqWnYXXXXXYYYY00000YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYXXXYYYYYYYYYYYYYYYYXXXYXnnWWWqqTebbrcccclllllllalllll..............................",
      "..................................bcjrccllcllcclbreTToqWWnYYYYYYYY0000000YYYYYYYYYYYYYYYYYYYYYYXYYYYYYYYYYYYYXYYYXYXYYXXYYYYYYYYYYYYYYYYYYXXnnnnnnqqmobrrrcccclllllaaallla..............................",
      "..................................ttmrrllcllccrcbeeeeUqWXXYYYYY00000111000YYYYYYYYYYYYYYYXXYYXXYYYYYYYXXYXXXXYXXXXXXXWWXXWWWXWWXnYYYXYYYYYYXXXnnnnnqqoeebrrccclllllaallla...............................",
      "..................................mchrrlcclclccrbbeToUWWXYYYY0000111100000YYYYXXXXXXXXXXXXXXXXXXXXYYYXXXXXXXXWXWWWWWWUUUqqqqqqWWWWWYXXYYYYYXXnXnXnWWUUTebbrclcllllllllll................................",
      "..................................jtjsbccllrbrbrrreTUqWXYYYY0011111100Y0XYXXXWXXWWWWXXXXWXWXXXXXXXXXXXXXWWWWWWUUTooedrrldeeeVToToqoqUqqYYYYXXYXnXnWWqUoTerrccclllllllaa.................................",
      "..................................ttjhrlclceerbrbreTUWWYYYY00001100YYYYXXXWWWWqWqWZWWWWWWWWWWXWWXXXXXXXXWZZWqUToVdrclbcrrcrreVdeVVoeTUWqXYYXXnYXnXnWqqoTerccccclllllall.................................",
      "..................................tcjhbrlclcrrrbrdToUWWYYY00011YYYXXWUUoUTeeerdrrdeeVoUUUZqWWWWWWWWXWWWWWWqqqoedddrllllllclcrcrrrceVTVTTooWXXnXYXnnnqqoeebrccllccllllal.................................",
      "..................................tccthclllrbbbrrbooUWXYYY000000YqqUUoTedrrcrccclrrrrdoTUUoZWWWWWXWWWWWWWUqToVVrrrllllclccclclrrrTedeeTeoUoWXnYXXnnnWqmTebrlcllllllllal.................................",
      "..................................tcctjcllcrccbrrbooUWXYYY00Y0XWWUWoTTeerclccclrcrlrreeTVoUUWWWWWWWWWWWWWqUTVVdedrrrclcrlcllllrrbreeedeTeTqTXXXXYnnXWWmoerrlccllcllllll.................................",
      "..................................bctthlllccrrrcrboUqXXYYYY0XoqWqoTddbclllllllcllllcbrVVeToUTUZWWWWWWWWZWZUToTVTerdrddrrrrrrTeeeooUoUUooTTmmoWnXnXXnnnqmebrccclcllllla..................................",
      "..................................tccthcllcrcbrrrbooqXXYYY00UqUUUoTdrrllllllllllllllbrrdVVToUZZWWWWWWWWZZUUUooToTTeVVVVrVeoTTooUoqWnqqqWoTVooonnXXXnnnqmebccccllllllll..................................",
      "..................................cccciclcllrrrrbroUqXXYYYqoTeVeVTTdeeedderrdrrrdVeeVTTTTToTUZZZWWWWWWWZZUUUooTToTTTTVTTTTooUqqUqWWnnnnnqomqqmUnnXXnnnWqobrlccllllllll..................................",
      "..................................tcccjclclcrrbbrroqWXXYYYoUoTeVdTToTeToTeeeeVVeVeeTTTTToTooUUqZWWWWWWWZZUUUooTTTTTTTVeTTToUqUqWWWWnnXnnnnWmqoonnXXnnnWqmbbbccllllllll..................................",
      "..................................tcccjrccrlclrrrroqWXYYWoWqUUooqqoqqUUUoooooTTTTTTTTeTTTTToUUZZWWXXXXXWZUUUoTTTVTTVVVdrrrVVToUqqWWWWWWXnqnqnUqqnnnXXnnfqebrrlcllllllll.................................",
      "..................................cccttcccleblrcrroqWXYYqnTqoqUqqUUqUUUUUooTooTTVVVVTTTTTTTUUUZWXXXXXXXWWUUUTTTTTVVddrrrdVTTVdVTUUZWWWWWWnnnnqqnUnXXYnnnqebrrllllllllll.................................",
      "..................................tccttccgcccccccrTqWYYYWWqqUqWWqqqUUUUUUUoToTVVVVVVVTTTTTooUUWWXYYYYYYXWUUUoTTTVVddrdVVTTUUqqqVdooUqqqWWnnWnWWonnXXXXnnqebrcclllllllll.................................",
      "..................................tcccttrllcccclccTqWYYnnWWWnWqqUUUoTVdToomoooTedrrdVVeeTTTUUZWWYY000YYXWZUUoTTVVVdVVTTTVTVVVTqqWoodToqZWnnnnWWnWnnnXXnnqebbcclcllllllll................................",
      "..................................ccccttbllclccccceqnYYYYnWnWWqUUoodrVomqmqooooVTddrdVVeTToUUZWXYY0000YXWUUUoTTTVVVVVTTdrdrdrVVTUqUodVUUWWnnnnnnnnXXYXnnfebbbclcllcllllc................................",
      "..................................cccccbbllclccccceqnYYYXnnWqqooTreooodrccllcrddeVVTVVVVVToqUZWXY000000YXWWqUoTTTTTTVdrecclclltjlrdUqmdTUqWnnnnnnWnXXXnnfeerbccclllllllccf..............................",
      "..................................ccctcjbllllrclcceqnYY0YnnWqUoTdToTerllclCccclrdVVTTVeeeToqqWWXY000010YYWWqUoTooTTVddomrbclaalcclldoooVoUqWnnnYnnnXXnnnfeerrrcllllllllccf..............................",
      "..................................cccccbbllclclccleUnYYYYYWWUoVdTedclbcccla2cjthmrrdToUoooUZZWXXY001000YYXWWZZZUVdrdeoqqbjbc222tcjellcTodTUWnnXnnnnnnXnnqTebrcccllllllllceH.............................",
      "..................................ccccccblcllrcclceUnYYYYYWWUorVerrcbbctc2222jjmmhdrVTqUUUUZZXXX00110000YXWWZZUorddVTTmqebjblcctcehrlldTTVoqWnnnnnnnnXnnWTebrccclllllllccrHH............................",
      "..................................cccctcjlcllrlccrbqnYYYYXnWUodTdccbbjctcc222jjmqoeerroUUUUZWXXY0011000YYXXWZZZWqUoooUUUobhhbbjbrheerlrdoTTUWnnnnnnnnXnnqTebrccccllcllcccjHH............................",
      "..................................ccccccjcccccclccemnYYYYXWWUTTdTrrdehecjjbjhedUUooTooqqUqUWWXYY0011000YYXXXXWZWqqZZUUUUUUqnnfqWqoTooTerVTUqqWXnnnnnXXnnWeerrccclllllllceiHHH3..........................",
      "..................................ccccccclclccllcceqYYYYYXWZooTddeTTTomjbjjooqmqUZUUWWWqUqWXXYYY01440000YYXXXXWqqUUUUUUUUooTUUTUUUUoUoqoTTUUqWXnnnnnXXnnfebrrcllcll2lllqWWMHHH..........................",
      "..................................cccccctrbbrrllllemn0YYYXWWUoUqWqUUqqqUUUUUUqZWqUUZUUUqZWXXYY0001440000YXXXXYXXqWqUoUUUqZUUZUUqqWWWWWnWnWWXXXXYYYXnXXnnWebbccllcllllUWXXXXXHwDD........................",
      "..................................cccccctcrbrcllcremnY0YYYXnZZnnnnnWWWWUqUqqWUWZZUUUqUqWWXXYYYY001141000YYYXXXXXWWWqUoT5UZUUUUUqqWWqWWnXXXYXXXXYYYXnnXnnWhbbrccllllcrWWXYYXXnwDDx.......................",
      "..................................cccccct0YobllccreqnY0Y00YYY0YYXWWWWWWZZZZqZUUTToUqZqWXXXXYYY0000110000YYXXXXXXXXXWWWUqU555UUUUUZqWWWXXYYYYYYYYYYXXnnnnqhebrcccccrdVXXXYYWZWXDxxxx.....................",
      "..................................ccccccM0YUblllrreUnY00000000YYYWWZZZUUUUUU5555UqWWZWXXYXXYYYY0001111000YYXXYXYYYYWWWWWWqU5UUUZZWWnXXXXXYYYYYYYYYYXXnnnqTerrccccrroZXXXWUV6ZWDxxxx.....................",
      "..................................ccccc1110UrlllrbeUnYYY0000000YXXWZUUU55oUoUqWWWWnXXYYYYYYYYY00001110000YYXYYYXYYYXXXXWWWWnWWWWWXXXXXYYYYYYYYYYYYYXXnnnWeebrcclcemqWWW5TT666Zxxxxxx....................",
      "..................................ccccc0000TrllcrreUnY0000010100YYYXWWZUUqZZWWWWXXXYYYYYYYYYY000011111000YYXYYYYYYYYYXXWWWnXXWXnXXYYYYYYYYYYYYYYYYYXnnnnWoerrcbrceUTZWU55TT65ZDxxxxx....................",
      "..................................ccccc7ZYYXdllcrrdUnY000011111000YYXXWWqWWWWWXXXYYYYYYYYY0YY000111111000YYYYXXYYYYYYYXXXXXXYXYXXYYYYYYYYYYYYYYYYYYXnnnnWTerccbccrTqWqq55T655ZHxxxxx....................",
      "..................................ccccc789UWrlldrbdon000001111110000YYYYYYXXXYYY000YYYYYY000Y001414411000YYYYYXYYYYYYYYYYYYYXYYYYYYYYYYYYYYYYYYYYYXXnnnnnobrccerTdWqqWWUU55998nDDDDx....................",
      "..................................ccccc7899ZVlcVrbeqn0000011110111100000YYY0YY00000Y00YYYYY0Y00414441100100YYYYYYY0YYYYY0YYYYYYXYYYYYYYYYYYYYYYYYYXXnnnnnoerrrTTUqUUqWWUUU5598XMEwDD....................",
      "..................................cccctXZ995TddTrbTqY000001011111111101001001100000000YYYYYY001114110000010YYXYYYY0YYYYY00YYYYYYYYYYYYYYYYYYYYYYYYYYnnnnnmorrdqqWWZqWXXZUU558ZXhbbew....................",
      "..................................cccthYZ955TTooedTUY0000101111114111111111110000000000YYYYY0111110000000100YYYYYYYYYYYYYY0YYYYYYYYYYYYYY0YYYYYYYYXXXnnnWmobreWqWUWWXXXWZU5587Xkbbbu....................",
      "..................................c2tmfYZ99555qUoeTqY000000011111141114411100100000000YYYYY00000000000Y0Y000YYXYYYYYY0YYY0YY0YYYYYYYY0YY0Y0YYYYYYYYYXnnnnoeboWWWnnXYYYXWWZZZZ7nebbb.....................",
      "..................................iiiggY799555qUUTeqY000000011141111111110111000000000YYYXY00YYYYY0Y0YYYYYYYYYYXYYYYY00YY00Y0YYY0YY0Y0YYYYY0YYYYYYYYXXnnnoTdWWZWWnYYYYYXWZZZZ7fbbbb.....................",
      "..................................uuMME079955oWqUoTqY000001001111111441101011000000YYYYYXY0YYXXYYYYYYYYYYYYYYYYYXYYYY000Y0000YY000000Y00Y0YYYYYYYYYXXnnnnooenWZWUWYYYYYXXWWZZ7fhbbb.....................",
      "..................................wwwww0X99995XXq5TWY0000000000001111111011000100000YYXXY00YXWWWXXXXXXXXXXXWXXYYYXXXYYYY000Y00000000000000YYYYYYYYYYXnnnnmTqnqWV65XXYY0XX7777Ygshb......................",
      "..................................wSSSw0X9999ZXXnUTWY0000000000001111011111000000Y0YYX7X000X7WZZWWX77XXXXWWWWXYYYXXXYYYY00YY0000000000000Y0YYYYYYYYYnnnnnqonnqVdTUWXXYYYX777XYgshk......................",
      "..................................Swwww4YZ955XXXZ5UWY0000000000111111111110100Y00YYYXXY00YYWWZZqZZZZZWWWWZqZZZXXYYXXXYYYY000000000000000000YYYYYYYYYYXnnnqonYWVV5UW7XYYYX777YYIII.......................",
      "..................................CwwwwSYZ895YXWU5UWYY000000001111111111110000000YXY7700YX7ZUUUUUUUZZZZWWZZUUZWXXYYXXYYY0Y000000000000000Y0YYYYYYYYYXnnnnqTYYYV65UW77XYY7777XXiii.......................",
      "...................................wwwwwn7Z55YXWUUToY00Y0Y00001111111001100Y0YYYYYXXXXYYXWZ5rl2aTUUUUUUUZl22ll5Z7XX7X77XYYYYY0Y0000000000000YYYYYYYYnXnnnqqYYYT55ZZWWXXYX77XXfi.........................",
      "...................................wwwwwHX7550XWUUUnY0Y0000000011111110100000YYYYXXX77YX7Z5ll222l55555UUTl22llT5WWWXX77XYYYY0000Y0000000000YYYYYYYYXXnnnnWnYY0q5UZZWWXYYXXXYnss.........................",
      "...................................Cwwwww77880XWUUq0Y000000000001110010000000YYYX7X77XX7ZU5ll22lrd5555UUVr22lrV5ZZWXX77XXXYYYYY0Y000000000YYYYYYYYYYXnnnnnnYYYWUZZWZWXXYX7YYgg..........................",
      "....................................wwwwwXX7Z0XWqU000Y000000000000000000YYYYYYYXXX7XXXZZZ5VrrlldVT5T55UooTrrVVT5UZZXXXXX77XYYYY0Y00Y0000YYYYYYYYYYYYXnnnnnnYYYXWZZW77XYY7XYYgh..........................",
      "....................................xwwwwEYY7YXWZU000Y000000000000000000YY0YYYYXX7XXX7ZU556VrdVTTT5TT55UUUoVT555UZWXXXXX77XXXYYYYYYY0YYYYYYYYYYYYYYYYnnnnnnYYYXXWW77XXYY7XYgs...........................",
      "......................................HHwHH0YYYXZZ0000Y0000000000Y000YYYXYXYXX777XXYYXWU5TT5UUU5T5T5TT5oUUqqWZ55ZWWYYYXX7777XXXYYYYYYYYYYYYYYYYYYYYYYnnnnnnYYYXYYXXXXYY7XYfh............................",
      ".......................................HHHHYYYYYWZ0Y0YYY00Y00Y00Y0YYYYYYYX7XX7777XXYYYYW56T5UUUU5TTTTTT5UUqqZZ5UWXXYYYXX7WWWXXXYYYYYYYYYYYYYYYYYYYYYnnnnnnnYYXXYXXXXXYYWXYhj............................",
      "........................................HHHEY000YXYY0YYYYYYYYYYYYYYYYYXXXX7X77WW7XXXY0YYXWUUUUUUUoTTTTT55UqZZWXYXYYYYYYXXWZWW77XXXXXXYYYYYYYYYYYYYYYnnnnnnnYnWXXXX7XXYYXYnK.............................",
      "........................................EHHHY010YXXY0YYYYYYYYYYYYYYYYXX7XX777W7WWXYY0000YXWZZZZUUU55TooUUWWWWXXYYYYYYXYXXXWZZWWXXXXXXXXYXYYYYYYYYYYYnnnnnnYYXZ7XXXYYYYYXYuz.............................",
      ".........................................HHHH0110YYY0YYYYYYYYYYYYYXYXXXXXXWW7ZZWWXYYY000YXWWZqZZqUUU55UUUWWXXXYYXYYYYYYYXXWWZZ77XXXXXXXXYYYXYYYYYYYXnnnnnnYYZ57YYY00YXWYgK..............................",
      ".........................................HHEEE01100Y0YYXYYYYXYXYXXXXXX7777WZZZZW7YYY00000YYXWWWWZqqqqZZWWWXXYYYYYYYYYXYYXX77WWWWW77XXXXXXXXYYYYYYXYXYnnnnnnXZ7YYYYXXWZXnKK..............................",
      "..........................................EHEHY1110YYYYXYYYXXXXXXXXXW7WWWZZZZZW7XYYY000000YXXWWWWWZWWWWWXXXYYYYYYYYXYYXYXXXXWWWW77WWWWXXXXXXYYXYYXXYnnnnnnnXXYYY0YWZ8XYuKK..............................",
      "...........................................EEE001100YYYXXXXXXXXXXX7WWWWWZZZZZZWXYYYY00000000YXXXWWWWWWWXXXXYYXYYYYYYYYYXXXXXXW7ZWWWWW7XXXXXXXXXXYYXYnnnnnnnXYYYYYYZXXYXKK...............................",
      "...........................................EEEM011100YYXXXXXXXXWWWWWWZWZZZZUZWWXYY00000000000YXXXWWXXXXXXXYYYYYYYYYYYYYYXXX777WWWWWXWWXXXXXXXXXXXYYXnnnnnnnXYYYYYYXYYYuKK...............................",
      "............................................EEEY11011YXXXXXXXWWWWWWZWZZZZZZZZWXYYY0000000001000YYXXXXXXXXYYYYYYYYYYYYYYYXXXXWWWWWWWWWWWWWXXXXXXXXXnnnnnnnnnXXXYYYYYYYuJs................................",
      "............................................HMMM00000YXXXXWWXWWWWWWqZqZZZZZWWXXYY0000000100000000YXXXXXXXYXYYYYYYYYYYYYYYXXXXWWWWWWWWWWWWWWXXXXXXXnXnnnnnnnXXXYYYYYYYJN.................................",
      ".............................................MME0Y00YYXXXXWWWWWWWqZZqZqZZZWWWXXYYY0000000000000000YYXXXYXXYXYYYYYYYYYYYYYXnXWWWWWWZWWWWWWWWXXXXXXXnXnnnnnnnXXXYYYYYYnNN.................................",
      "..............................................MM0XYYXXYXXWWWWWWWWZZZWZZZZZZWWXYYY00000000YYXXX777777BZZZZZWZWWXWXYYYYYYYXXXWWWWWWWWWWZWWWWXWXXXXXXnnnnnnnnWYYYYYYYngJN..................................",
      "..............................................MM0YYYYYYXXXWWWWWWZWWZWZZWZZWWXYYYY000000YYXXWZZZZZZZBZZUUUUUUZZWWXXXXYYYYXXWWWWWWWWWWWWWWWXWWWXXXXnnnnnnnnnWYYYYYYYguKN..................................",
      "..............................................MM00000YYXXnWWWWWWWZWWWWWWWWnXnXYYYYYYYYWZZUUUUUUU5UUU5U55UUUUUUUUUUqWWXXXXXWWUqZZWWWWWXWWWXWWWWXXXnnnnnnnnWWXXXXYXnyys...................................",
      "..............................................MMY0000YYXXWWWqqWWWZWZZWWWWWXWXXXYYYYYXWUUUUU5UUUU5555555T55U5UUUUU5UqWWXXnWWqUUqWWXXX77WWWWWWWnnXXXnnnnnnnZZXXXXXnsjjy...................................",
      "..............................................MuYY000YXXnnWWqWWWWWWWWWWXXXXWWXWXXWZUTTT55TTTTTTTTTVVVVTTTTTTTTTTTTTTToUUqqoTTTUWW7XXXXXWXWnWXnnXXnnnnnnnn5UZZWWWyQQ.....................................",
      "..............................................MMMYYYYYXnXXWWqWWWWWWWWWXXXXXWWWWZZU5TTTTTTVVVVVdVVVddVToTVddVVVVVTTTTTTTTooTTT5UWW7XXXXXWXXXnnXXXXXnnnnnnnTTUUUmKyQy.....................................",
      "..............................................MMMnYYXX7nXXnWWWWWWWWW7WXXXXXWWZUUUTTTTTTVVdrrrrVTooVVoUqmoVVToTddVVVTTTTVTVVVT55WWX7XXXXWXnnXWXWnXXnnnnnnnbbsIKKKyy......................................",
      "..............................................uuuuWWZZUXnXnnWWWWWWWWX7XXXXXWZoTTVVVVVddVVrVoVVqqffqonnnnnoqqqqTTooTdVlll22rToUZWWXXXXXXWXXXXXXnXXXnnnnnnnjcNKKKKya......................................",
      "..............................................uuuuufUU5XXXXWWWWWWWWWXXXXXX7WZ5VdrrrrrrVeeVoqUTqnnnnqnnnnnUnnnfToUUoeecclalT55UUWWXXXXXXXXXnXnWXnnXXnnnnnnccKKKKKI.......................................",
      "...............................................guuugggggnXWXWWWWWWXWXXXX7XWWWUol2a2lrrTooVqnnmnnnnnWnnnnnfnnnfloqqlddlrrUZZUZZZWWXXXXXXXXXXnWXnXnXnnnnnnmttyKKKK........................................",
      "................................................ugggggggnXWXWWWWWWWXXXXXXXWWWWqTd22lrreoorqnnqfnnnnWnnnnnWWnWqlVqolddVVUWWWWZZZ7XXXXXXXXXXXXXXXnnXXnnnnnhjtsKKKK........................................",
      ".................................................MggggggnXnnnWnWWWWXXXXXXXXXXXWWWUTVVVdrrllqWrofWWndWWnnmrrd55UUZZWXWXXXXXWWWWWXXXXXXXXXXXXXnnXnXXXnnnnnbtyKKKN.........................................",
      "..................................................ggggggnnXWXXXWWXXXnXXXXXXXXXXXXWUU5TTTTTTVddrrrrrrdrrdVU5UUZWWWWXXXYYYYYX7XXX7XXXXXXXXXWXnXnXXXXnnnnnntyKKKK..........................................",
      "..................................................gggggggnXnXnWWWXXXXXXXXXXXXXYYYYXWZ5UUUUUU555U5U955UU8ZWWBWWWXXXXXXYYYYYXXXXXXXXXXXXXXXXXXXnnXXnnnnnngjsKKKK..........................................",
      "....................................................gggggnXXXXXXWWWXXXXXXXXXYYYYYYYYYYYYYYY0111YXYXWYXXWXXXXXXXXXYYYYYYYYYYYYXXXXXXXXXXXXXXXXXnnnnnnnnnisKKKK...........................................",
      "....................................................gggggnnXnXWXWWWXXXXXXXYYYYYY000YYYYYYYYYYYYYYXYYYXXXYYXXXXXXXYXYYYYYYYYYXXXXXXXXXXXXXXXXXXXnnnnnnnnILKKKK...........................................",
      ".....................................................gggggnWXXXXWXXWXXXXXXXYYYYY0000YYYYXYYXXXXXYYYYYYYXXWXWXXXXXXYYYYYYYYYYYYYXXXXXXXXXXXXWnnXnnnnnnnnsKKss............................................",
      ".....................................................gggggnWnWWWWWXWXXXXXXYYYYYYY0000YYXXXXXXXXXXXXXXXYXXW7X7WXXXYYYYYYYYYYYYYXXXXXXXXnXXXXnnnXnnnnnnnnsKIy.............................................",
      ".....................................................gggggnnWWWWWWWXXXXXXXYYYY000Y0000YYXWWWWWWWWWWWWWZWWWWWWWXXYYYYYYYYYYYYYYXXXXXXXXXXnnnnnWnnnnnnnnnKKQj.............................................",
      ".....................................................gggggnnnWnWWWWXXXXWXYYYYY000Y0YYYYYYYXWZZZZZZZZZZZZUZWWWXXXXYYYYYYYYYYYYYYXXXXXXXXXXnXnXnnWnnnnnnnKKQQ.............................................",
      ".....................................................gggggnnWWWWWqWXXXWXXYYYYYY00YY000YYYYYWWZUUU5UUUUUUqZWWXnXXYXXYYYYYYYYYYYYXXXXXnnnnXXXXnWnnnWnnnnnNOyy.............................................",
      "......................................................gggggnWWWWWWWWWWWWXXXXYYYYYY0YYYYXXXXXXWWWWWqZWWWWWWXXXXXXXXXXYYYYYYYYYYYXXXXnXnnXXXnXXnnWnnnnnnnNKO..............................................",
      "......................................................gggggnWWWWWWWWWWWWXXXXY0YYYYYYYYYXXXXXXWWWWWqqZWWWWWXWXXXXXXXYYYYYYYYYYYYXXXXnnXnXXnnWnnnnnWnfnnnKRK..............................................",
      ".......................................................gggggWWWWWWWWWWWWXXYYYYYYYYYYYYYXXXXXXXXXWWWWWXXXXXXXXXXYXYYYYYYYYYYYYYYYXXXXXXXXXnWnnnnnnnWnnnnNN...............................................",
      ".......................................................gggggWWWWWWWWWWWXXXYYYYYYYYYYYYYYYYYYYYYYXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYXXXXXXXXXnWnWWnWnnnWnnnnNN...............................................",
      ".......................................................gggggnWWWWWWWWWWXXXYYYYYY0YYYYYYYYYYYYYYYYYYXYYYYYYYYYYYYYYYYYYYYYYYYYYYXYnXXXnnnnnnnnnWnnfnnnnnNs...............................................",
      ".......................................................ggggggnWWqWWWWWWXXXYYYYYY000YY0YYYYYYYYYY0YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYXnnXnXXnnnnnnnWWfffnnnnnN................................................",
      ".......................................................aggggnnWqWqWWWWWXXXYYYYYY00000000000000000000Y00YYYYYYYYYYYYYYYYYYYYYYXnnnnXXXXnnnnnWWnWfffnnnnnN................................................",
      "........................................................ggggggfWWWWWWWWXXXYYYYYYYYY00000011111111100010000000000YYYYYYYYYY0YYYYYnnXXXXnnnnnWWWWffnnnnnn.................................................",
      ".........................................................gggngnWqqWqWWWXXYXYYY0YY0000001111111111111110000000000000000YYYYYYYYYYYnnXnnnnnWWWWfqfWnnnnnn.................................................",
      "..........................................................gngngnqqWWWWWWXXYYYYY00011111111111111011110000000000000000Y0YYYYYYYYYnnnnnnnnnnWWWqWffnnnnn..................................................",
      "..........................................................ggggggfqqWWWWWXXXXYYY0011111111111111111111100000000000000000YYYYYYYYnnnnnnnnnnWWWqfffnnnnnn..................................................",
      "..........................................................hnggggnqqqqWWXXXXXXYY000111111111111101000010000000000000000YY0YYYYYnnnnnnnnnWWWWqqqfnnnnnnnn.................................................",
      "...........................................................fgngggWqqqWWWXnXXXYY00Y1111111111111100000000000000YY0000000YYYYYYYnnnnnnnWnWWqqqqffnnnnnnnnKN...............................................",
      "............................................................gngngnqqqWWWWXXYYYY0000011100000000000000000000000YYY0000YYYYYYYnYnnnnnnnnWWqqqqqfWnnnnnnYnsy...............................................",
      ".............................................................sgggnnqqqqWWnnXXYY000000000000000YY0YYY000Y00YYY000YY0YYYYYYYYnnnnnnnnnnWffqqqqqWWnnnnnYnnIQjt.............................................",
      "..............................................................gggnnqUqqqWWnnnYYY0Y0000000000YYYYY0YYYYYYYYYYYY0Y0YYYYYYYYYYnnnnnnnnWWWqqqqqqqnWnnnnnnnnsQtttt...........................................",
      "..............................................................gnggnnWUqUWWWnXXXXYYYYYYYYYYXYXYYYXXYXYYYYXYYYYXYYYYYYYYYnnnnWnnnnnnnWWqqqqqqfWWnnnnnnnYnftc2cc2..........................................",
      "..............................................................ggggYWWqUUUqWWWXXXXXXYYYYXYXXYYXXXXXXXXXYXXXYYYXYXXXYYYXnnnnnnnnnnWWWqqqmqqqqWWnnnnnnnnnngc22222..........................................",
      "..............................................................nnggnnnWqoUUWqqWnnXXXXXXXXXXX7WWWWWWWWWXXXXXXXXXXXXWYXnnnnnnqWWqWWqqqqqqqqqfqWWnnnnnnnnYngc22222..........................................",
      "..............................................................ggggnnnWqUooqqUWWWnXXXXXXWXWWWWWWWWWWWWWWWWXXXXXXXXXWnnnWWnWWqqqqqqqqmmqqqWqWWWnnnnnYYYYYg222222..........................................",
      "..............................................................ggggnXnWqqoooUUqWWWWXXWWWWWWWWWWWWWWWWWWWWWWWWWWnXWWWWWWWWfWfqqqqqqqmqqqqqqfWWWnnnnYnnnYnnjc2222..........................................",
      "..............................................................gggggXXXWqmmTooUUUUUqqWWUZqqqqqqqqqUqZqWqqqqWWWqqqWWWWWqqqqqqqqmmmqqqqfqqfWWWWnnnnnnYnYYYnhtt222..........................................",
      "..............................................................ggggnXnnWWqmoooooUoUUoUqUUUqUqUUqUqUqUqUUqUqUZUqqqqWqqqmUqqqmqmmmmmqqqqqqqWWWWWnnnnnnYYnYnh2c222..........................................",
      "..............................................................ggggnXXnWWqqooUoooooooooUUooUUUUooooooooUUUUUqUUUUqUqUqmmmmmmmmmmqqqqqqWqWWWWnnnnnnYnYYYYYgc2222a.........................................",
      "..............................................................gggggXXXnWqqUUUoooTooooooooooooooooooooTooooooooUUooommmmmmommmmqqqqqqqqWWWWWnnnnnnnnYYYYngcc2222.........................................",
      "..............................................................gggggYXXWWWqqUUUoooTTTeeeeeeeToTeTTTTTeeeeTTTTTToTooooooooommmqqqqqqqWWqqUWWWnnnnnYnnYYnYYgcc222ccc.......................................",
      "..............................................................nggggYXXnnWqqqqmooooTTeVeeeVVeTeeeeeeeeeeeeeeTTTTToooooooommmqqqqqqqWfWqqqWWWnnnnnnnYYYYYYYcc22ccccyRR....................................",
      "..............................................................gggggYYXnWWWqUmmoooooTTeVVeeVVVVVeeVVVeVeeeVeeTeeTooooooomqmqUqqqqqqqqWqWWWWWWnnnnYnYYYYYYYtt2ccccFRRR....................................",
      "..............................................................ngnggYYXnWWWqUUomoooooTTTTTeeeeeeeeeeeTTeeeTTTTToToooomommmqmqqqqqqqWWWWWWWWWnnnnYnYYYYYYYYshtccQRRRRR....................................",
      "..............................................................nggggYXYnnWWqqqmooUoooooTTTeTTeeTeeTTeeeeeeTTToTTooooooommmmqqqqqqqqqWqWWWWWnnnXXYYYYYYYYYYQhttcRRRRRK....................................",
      "..............................................................ngnggYYYnnWWqqqqUUUoooooTTTTeeTTeeeeeeeTTeTTTTToooooooommmmmqqqqqqfqqqqqWWWnnnnXYYYYYYYYYYYfhQRRRRRRa.....................................",
      "..............................................................nngggYYXnnWWWqqUUUUooooooTTTTeTTTTeTTToTTTeoTTTooooooommmmqmqqqqfqfqfqWWWWWnnnXnXYYYYYYYYYYgjRRRRRRR......................................",
      "..............................................................nggggYYXXnnWWqqUqUUooooooooooTTTTeTTeTTTTeeTTTToooooooommmqqqqfWqfqqqqWWWnnnXnnXYXYYYYYYYYgFFORRzRR.......................................",
      "..............................................................gnnggYYYXnWWqqqqqUUUUooooTTToTTTTTTTTeTTTTTTTTooooooooommqmqqqWffffqqqWWWWnnnXnXXXYYYYYYYsQQQQQFOR........................................",
      "..............................................................nngggYYYXnnWWqqqqUUUoooooooooooToToeTToTTTTTToooooooomommqqqqfWfWWWqqWWWWWnnnXnXXYYYYYYYFFFQQQQQQF........................................",
      "..............................................................nngggYYYXXWWWWqqqqqUUUUoooooooTToTTTTTTTTToooooooooooomqqmqqffffWqWqWWWWWWXnXXXXXYYYYYFQQQQQFQQQ..........................................",
      "..............................................................gnnggYYYXXnnWWqqqqUUUUmUoooooooooToTTTTooTooooooooommmmmqqqqfnfnWWWWWWWWnWnnnnXYYXYYsFQQQQQQFFFQ..........................................",
      "..............................................................nngggYYYXYnnWqqqqqqqUqUUmooooooooooooooooooooooooommmomqqqfffffffWWWWWWWnnnXnXXYXnIQFQQFFFFQQQ............................................",
      "..............................................................ngnngYYYXXnnWWWqqqqqUUUmmooooooooooToooooooooooooommmmqqqqWWWWWnnnWWWWnWWXnnnYXXnFFFFFFFQQQQQ.............................................",
      "..............................................................gggggYYYYnnnWWWWqqqqUqqUUUUoooooooToooooooooooooommmmqqqqWWnnnWnnnnWWWnWnnnXXfFFFQFFFQQQQQQ...............................................",
      "..............................................................ngggmYYYXXnnnnWWqqqqqqqUUUUUooooooooooooooooooooommUUqqqWWWWnnWWWWWnnnnnnnnnIQFFFFFFFQQQQQG...............................................",
      "..............................................................ggfccYYYYXnnnWWqqqqqqUUqUUqUooooooooooooooooooooommqqqqqWqWnWWnWnqnnnWWnnnIQQFFFQQQQQFQQQ.................................................",
      "..............................................................QQQt2YYYYXnnnWWWWqqqUqqqooUUoooooooooooooooooomUUmmqqqqWWWWWWnWWWnnnnnfIFQFQQFQQFFQQQQF...................................................",
      "..............................................................QQQQQgYYYYXnnnWWWqqqqqqUmoUUooooUoooooooooUoooUUqmqqqqqWWWWWWWWnnWWnfQQQFQFQQQQFQQQQQF....................................................",
      "..............................................................FQFFQQQQQInXXWWWWqqqqqqqUUUUUooooooooooooooUUoUUqUqqqqqWWWWWWWnfIQQFFQQFQQQQFFFFQFFF......................................................",
      "..............................................................QQQFQQQQQQFFfWWWWWqqqqqqqUUoUUUoooooooooUoooUoqUqqqUqqqWqqWWffQQQQFFQQQQFQQQFFFQQFQ.......................................................",
      "..............................................................yFQQQQQQQQQQQQFQQyiqqqqqmUUUoooooooooUUUoUUUUUUqqqqqqqqiyFFQQFFFQQQQQFFQFQQFFQFFF.........................................................",
      "..............................................................aFFQQQFQQQQQQQQQFFQQQQiimUUUUoUooooooooUUoUoUUqqqqiiiFQFFQQFQFFFQQQQQFQQQQFFQFF...........................................................",
    ],
    colors: {
      a: "rgba(0, 0, 0, 1)",
      b: "rgba(55, 55, 33, 1)",
      c: "rgba(35, 38, 20, 1)",
      d: "rgba(73, 36, 36, 1)",
      e: "rgba(80, 64, 48, 1)",
      f: "rgba(126, 118, 106, 1)",
      g: "rgba(142, 139, 134, 1)",
      h: "rgba(81, 79, 69, 1)",
      i: "rgba(101, 97, 103, 1)",
      j: "rgba(64, 64, 64, 1)",
      k: "rgba(96, 96, 64, 1)",
      l: "rgba(31, 18, 8, 1)",
      m: "rgba(108, 95, 80, 1)",
      n: "rgba(154, 133, 111, 1)",
      o: "rgba(106, 78, 65, 1)",
      p: "rgba(51, 51, 0, 1)",
      q: "rgba(130, 101, 82, 1)",
      r: "rgba(56, 35, 25, 1)",
      s: "rgba(115, 126, 121, 1)",
      t: "rgba(43, 49, 53, 1)",
      u: "rgba(150, 155, 156, 1)",
      v: "rgba(188, 202, 213, 1)",
      w: "rgba(212, 211, 208, 1)",
      x: "rgba(255, 255, 251, 1)",
      y: "rgba(78, 111, 111, 1)",
      z: "rgba(146, 161, 198, 1)",
      A: "rgba(102, 102, 153, 1)",
      B: "rgba(170, 85, 85, 1)",
      C: "rgba(214, 222, 233, 1)",
      D: "rgba(229, 240, 252, 1)",
      E: "rgba(177, 182, 177, 1)",
      F: "rgba(81, 104, 156, 1)",
      G: "rgba(85, 85, 170, 1)",
      H: "rgba(198, 196, 196, 1)",
      I: "rgba(101, 111, 120, 1)",
      J: "rgba(156, 173, 182, 1)",
      K: "rgba(121, 155, 157, 1)",
      L: "rgba(119, 127, 155, 1)",
      M: "rgba(176, 168, 161, 1)",
      N: "rgba(153, 190, 194, 1)",
      O: "rgba(92, 119, 170, 1)",
      P: "rgba(128, 128, 64, 1)",
      Q: "rgba(65, 81, 100, 1)",
      R: "rgba(119, 140, 181, 1)",
      S: "rgba(221, 227, 200, 1)",
      T: "rgba(100, 66, 49, 1)",
      U: "rgba(127, 85, 68, 1)",
      V: "rgba(88, 51, 33, 1)",
      W: "rgba(153, 108, 89, 1)",
      X: "rgba(173, 128, 103, 1)",
      Y: "rgba(186, 142, 123, 1)",
      Z: "rgba(147, 97, 72, 1)",
      0: "rgba(205, 159, 139, 1)",
      1: "rgba(216, 172, 159, 1)",
      2: "rgba(12, 13, 13, 1)",
      3: "rgba(213, 213, 170, 1)",
      4: "rgba(228, 191, 174, 1)",
      5: "rgba(124, 72, 51, 1)",
      6: "rgba(109, 50, 30, 1)",
      7: "rgba(172, 116, 83, 1)",
      8: "rgba(150, 82, 48, 1)",
      9: "rgba(129, 57, 36, 1)",
    },
    stats: {},
  },
  SPIDER: {
    label: "Spider",
    ctor: Mob,
    image: [".......vvvvv......", "......vhihhhv.....", ".....vhhhhhihv....", ".....vhhhhhhhv....", "....vvvvvvvvv.....", "....lllrrllrrll...", "...l..rr.l.rr.ll..", "..l..r...l...r.ll.", "..l..r...l...r..l."],
    colors: {
      h: "rgba(150, 76, 182, 1)",
      v: "rgba(146, 120, 158, 1)",
      l: "rgba(69, 24, 83, 1)",
      r: "rgba(82, 52, 88, 1)",
      i: "rgba(0, 0, 0, 1)",
    },
    stats: {
      hp: 10,
      moveDrag: 0,
      projFreq: 0.7,
      projType: "PROJ",
    },
  },
  Octopus: {
    label: "Octopus",
    ctor: Mob,
    image: [".......hhhhh......", ".....hhhhhhhhh....", "......hhhhhhh.....", ".....l.r.l.r..l...", "....l..r..l.r..l..", "....l..r..l.r..l..", "....l.r...l..r.l..", "....l.r...l..r.l..	"],
    colors: {
      h: "rgba(177, 136, 136, 1)",
      l: "rgba(64, 114, 121, 1)",
      r: "rgba(83, 96, 139, 1)",
    },
    stats: {
      hp: 10,
      moveDrag: 0.01,
    },
  },
  0: {
    label: "Player",
    ctor: Player,
    image: [""],
    colors: {},
    stats: {},
  },
  LONGBOY: {
    label: "LongBoy",
    ctor: Mob,
    image: ["........hhh.......", ".......hhhhh......", "........hh........", "......tttttt......", ".....g.tttt.d.....", ".....g.llrr.d.....", ".......llr........", ".......llr........", ".......llr........", ".......llr........", ".......llr........	"],
    colors: {
      h: "rgba(136, 161, 177, 1)",
      t: "rgba(52, 58, 69, 1)",
      g: "rgba(166, 190, 183, 1)",
      d: "rgba(177, 204, 187, 1)",
      l: "rgba(184, 213, 204, 1)",
      r: "rgba(95, 112, 114, 1)",
    },
    stats: {
      hp: 15,
    },
  },
  BOSS: {
    label: "Boss",
    ctor: Mob,
    image: [
      ".......................",
      "........t..............",
      ".......ttt.............",
      "......t.t.t............",
      ".....ttttttt...........",
      "....ttttttttt..........",
      ".....ttttttt.......wwww",
      "...ggtttttttdd.....wwww",
      "..gggtttttttddd....wwww",
      ".ggg.ttttttt.ddd...w...",
      ".gg...ttttt...dd.ww....",
      "gg....ttttt....ddw.....",
      "gg....ttttt....dd......",
      "......ttttt............",
      "......llrrr............",
      "......llrrr............",
      "......llrrr............",
      "......llrrr............",
      "......llrrr............",
      "......llrrr............",
    ],
    colors: {
      h: "rgba(136, 161, 177, 1)",
      w: "rgba(51, 121, 174, 1)",
      t: "rgba(52, 58, 69, 1)",
      g: "rgba(166, 190, 183, 1)",
      d: "rgba(177, 204, 187, 1)",
      l: "rgba(184, 213, 204, 1)",
      r: "rgba(95, 112, 114, 1)",
    },
    stats: {
      hp: 50,
    },
  },
  ROB: {
    label: "ROB",
    ctor: Mob,
    image: [
      "..............................................",
      "..............................................",
      "...............tttttttttttttttt...............",
      ".............tttttttttttttttttttt.............",
      "...........gggghhhhhhhhhhhhhhhhgggg...........",
      "..........gggghhhhhhhhhhhhhhhhhhgggg..........",
      "...........gggghhhhiihhhhiihhhhgggg...........",
      "............ggghhhhhhnnnnhhhhhhggg............",
      "............ggghhhhhhnnnnhhhhhhggg............",
      "............gghhhhmmmmmmmmmmhhhhgg............",
      "..............gghhhhhhhhhhhhhhgg..............",
      "..................hhhhhhhhhh..................",
      "...................hhhhhhhh...................",
      "....................hhhhhh....................",
      ".....................hhhh.....................",
      "........aaaaaaaaaaHHHHHHHHHHaaaaaaaaaa........",
      ".......aaaaaaaaaaaaHHHHHHHHaaaaaaaaaaaa.......",
      ".......aaaaaaaaaaaaHHHHHHHHaaaaaaaaaaaa.......",
      ".......aaaaaaaaaaaaHHHHHHHHaaaaaaaaaaaa.......",
      ".........cccccccccccccccccccccccccccc.........",
      ".........cccccccccccccccccccccccccccc.........",
      ".........cccccccccccccccccccccccccccc.........",
      ".........cccccccccccccccccccccccccccc.........",
      "......lllcccccccccccccccccccccccccccc.........",
      ".....lllll..bbbbbbbbbbbbbbbbbbbbbb............",
      "....llll....bbbbbbbbbbbbbbbbbbbbbb............",
      "..llllll....bbbbbbbbbbbbbbbbbbbbbb............",
      "..llllll....bbbbbbbbbbbbbbbbbbbbbb............",
      "..llllll.....bbbbbbbbbbbbbbbbbbbb.............",
      "..llll........bbbbbbbbbbbbbbbbbb..............",
      "..............wwwwwwwwwwwwwwwwww..............",
      "..............wwwwwwwwwwwwwwwwww..............",
      "..............wwwwwwww.wwwwwwwww..............",
      "..............wwwwwwww..wwwwwwww..............",
      "..............wwwwwww....wwwwwww..............",
      "..............llllll......rrrrr...............",
      "..............llllll......rrrrr...............",
      "..............llllll......rrrrr...............",
      "..............llllll......rrrrr...............",
      "..............llllll......rrrrr...............",
      "................llll......rrrr................",
      "................llll......rrrr................",
      "................llll......rrrr................",
      "................llll......rrrr................",
      "...............llllll....rrrrrr...............",
      "...............llllll....rrrrrr...............",
    ],
    colors: {
      h: "rgba(136, 161, 177, 1)",
      w: "rgba(16, 47, 71, 1)",
      c: "rgba(20, 75, 59, 1)",
      t: "rgba(52, 58, 69, 1)",
      g: "rgba(29, 67, 56, 1)",
      d: "rgba(33, 82, 51, 1)",
      l: "rgba(24, 63, 51, 1)",
      r: "rgba(95, 112, 114, 1)",
    },
    stats: {
      hp: 1000,
      moveSpeed: 0.2,
      moveDrag: 0.01,
      projForce: 10,
    },
  },

  DOOR: {
    label: "Door",
    ctor: Door,
    image: ["tttttttttttt", "trrrrrrrrrrt", "trrrrrrrrrrt", "trrrrrrrrrrt", "trrrrrrrrrrt", "trrrrrrrrrrt", "trrrrrrrrrrt", "trrrrrrrrrrt", "trrrrrrrrrrt", "trrrrrrrrrrt", "trrrrrrrrrrt", "trrrrrrrrrrt", "trrrrrrrrrrt", "tttttttttttt"],
    colors: {
      t: "rgba(177, 136, 136, 1)",
      r: "rgba(186, 186, 44, 1)",
    },
    stats: {},
  },
  COIN: {
    label: "Coin",
    ctor: Collectible,
    image: ["..t...", ".tgt..", "..tt.."],
    colors: {
      t: "rgba(235, 76, 28, 1)",
      t: "rgba(202, 183, 45, 1)",
    },
    stats: {
      type: "currency",
    },
  },
  WEAPON: {
    label: "Weapon",
    ctor: Collectible,
    image: ["..ttttt", ".t.t...", "..tt..."],
    colors: {
      t: "rgba(85, 24, 107, 1)",
      g: "rgba(202, 183, 45, 1)",
    },
    stats: {
      type: "currency",
    },
  },
};
function getEntFormsButtonData() {
  const out = [];

  for (const key in ENT_DATA) {
    const ent = ENT_DATA[key];
    const firstColorKey = Object.keys(ent.colors)[0];
    const color = ent.colors[firstColorKey];

    out.push({
      key,
      color,
    });
  }
  return out;
}

function getEntOfIndex(index) {
  const keys = Object.keys(ENT_DATA);
  const k = keys[index];
  const base = ENT_DATA[k];
  return {
    label: base.label,
    ctor: base.ctor,
    image: [...base.image],
    colors: { ...base.colors },
    stats: { ...base.stats },
  };
}

function getEntOfType(type) {
  const keys = Object.keys(ENT_DATA);
  if (keys.indexOf(type) === -1) type = String(type).toUpperCase();
  if (keys.indexOf(type) === -1) return;
  const base = ENT_DATA[type];
  return {
    label: base.label,
    ctor: base.ctor,
    image: [...base.image],
    colors: { ...base.colors },
    stats: { ...base.stats },
  };
}

function getMobData() {
  const keys = Object.keys(ENT_DATA);
  return getEntOfIndex(r_range(0, keys.length - 1));
}
